export const textOptions = [  "apple",
    "banana",
    "cherry",
    "oatmeal",
    "elephant",
    "falcon",
    "grape",
    "honeydew",
    "island",
    "jungle",
    "kite",
    "lemon",
    "mountain",
    "nectar",
    "ocean",
    "penguin",
    "quartz",
    "rainbow",
    "sunflower",
    "tigerpaws",
    "umbrella",
    "violet",
    "waterfall",
    "xylophone",
    "yacht",
    "zebra",
    "infrared",
    "dandelion",
    "ember",
    "forest",];
export const backgroundColors = ["#F6E3D8", "#E8DFF5", "#DFF5E6", "#FDE2E2", "#FFE5D4", "#FFF9D9"];
export const textColors = ["#3A1C47", "#2C3E24", "#2E2E2E"];
export const heightRange = [200, 300];
